# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-29 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_creditcarddetail_orderpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcarddetail',
            name='credit_type',
            field=models.CharField(max_length=16, verbose_name='Credit Card Type'),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='optionName',
            field=models.CharField(help_text='The class name as defined in payment.py', max_length=20, unique=True, verbose_name='Option Name'),
        ),
    ]
