# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-29 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_model',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Shipping Models'),
        ),
        migrations.AlterField(
            model_name='orderauthorization',
            name='payment',
            field=models.CharField(blank=True, max_length=25, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment',
            field=models.CharField(blank=True, max_length=25, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='orderpaymentfailure',
            name='payment',
            field=models.CharField(blank=True, max_length=25, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='orderpendingpayment',
            name='payment',
            field=models.CharField(blank=True, max_length=25, verbose_name='Payment Method'),
        ),
    ]
