# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shipping_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='contact_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Contact id'),
        ),
    ]
