# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-19 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_paymentcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_company',
            field=models.CharField(blank=True, max_length=61, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_company',
            field=models.CharField(blank=True, max_length=61, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[(b'New', b'Pending'), (b'Back Ordered', b'Back Ordered'), (b'Payment Received', b'Payment Received'), (b'Complete', b'Complete'), (b'Front Office', b'Front Office'), (b'Front Office Called', b'Front Office Called'), (b'Estimate', b'Estimate'), (b'Net Terms', b'Net Terms'), (b'Contracts', b'Contracts'), (b'Target Room', b'Target Room'), (b'Flagged', b'Compliance Call Juli'), (b'Guns-GTG', b'Guns-GTG'), (b'Lowers', b'Lowers'), (b'Stealth Upper - GTG', b'Stealth Upper - GTG'), (b'NFA-Pending', b'NFA-Pending'), (b'Gun Room/Repair', b'Gun Room/Repair'), (b'Demo', b'Demo'), (b'Shipped', b'Shipped'), (b'Cancelled', b'Cancelled')], help_text='This is set automatically.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderauthorization',
            name='payment',
            field=models.CharField(blank=True, choices=[('STORE_CREDIT', 'Store Credit'), ('GIFT_CARDS', 'Gift Card'), ('AUTHNET', 'Credit Card')], max_length=25, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment',
            field=models.CharField(blank=True, choices=[('STORE_CREDIT', 'Store Credit'), ('GIFT_CARDS', 'Gift Card'), ('AUTHNET', 'Credit Card')], max_length=25, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='orderpaymentfailure',
            name='payment',
            field=models.CharField(blank=True, choices=[('STORE_CREDIT', 'Store Credit'), ('GIFT_CARDS', 'Gift Card'), ('AUTHNET', 'Credit Card')], max_length=25, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='orderpendingpayment',
            name='payment',
            field=models.CharField(blank=True, choices=[('STORE_CREDIT', 'Store Credit'), ('GIFT_CARDS', 'Gift Card'), ('AUTHNET', 'Credit Card')], max_length=25, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(blank=True, choices=[(b'New', b'Pending'), (b'Back Ordered', b'Back Ordered'), (b'Payment Received', b'Payment Received'), (b'Complete', b'Complete'), (b'Front Office', b'Front Office'), (b'Front Office Called', b'Front Office Called'), (b'Estimate', b'Estimate'), (b'Net Terms', b'Net Terms'), (b'Contracts', b'Contracts'), (b'Target Room', b'Target Room'), (b'Flagged', b'Compliance Call Juli'), (b'Guns-GTG', b'Guns-GTG'), (b'Lowers', b'Lowers'), (b'Stealth Upper - GTG', b'Stealth Upper - GTG'), (b'NFA-Pending', b'NFA-Pending'), (b'Gun Room/Repair', b'Gun Room/Repair'), (b'Demo', b'Demo'), (b'Shipped', b'Shipped'), (b'Cancelled', b'Cancelled')], max_length=20, verbose_name='Status'),
        ),
    ]
