# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-23 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_merge_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone Number'),
        ),
    ]
