# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-30 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_related_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricelookup',
            name='key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
